# Generated by Django 4.0 on 2022-01-03 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cabinet_medical',
            fields=[
                ('id_cabinet_medical', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('etaj', models.IntegerField(max_length=1)),
                ('corp_cladire', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('CNP_doctor', models.IntegerField(max_length=13, primary_key=True, serialize=False)),
                ('prenume', models.CharField(max_length=25)),
                ('nume', models.CharField(max_length=25)),
                ('telefon', models.IntegerField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=25, unique=True)),
                ('data_angajare', models.DateField()),
                ('salariu', models.IntegerField(max_length=8)),
                ('puncte_comision', models.FloatField(max_length=4)),
                ('denumire_specialitatate', models.CharField(max_length=20)),
                ('id_cabinet_medical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Baza_de_date_spital.cabinet_medical')),
            ],
        ),
        migrations.CreateModel(
            name='medicament',
            fields=[
                ('id_medicament', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('nume_medicament', models.CharField(max_length=20)),
                ('nume_producator', models.CharField(max_length=20)),
                ('forma_farmaceutica', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pacient',
            fields=[
                ('CNP_pacient', models.IntegerField(max_length=13, primary_key=True, serialize=False)),
                ('nume', models.CharField(max_length=25)),
                ('prenume', models.CharField(max_length=25)),
                ('telefon', models.IntegerField(max_length=20, unique=True)),
                ('sex', models.CharField(max_length=8)),
                ('data_nasterii', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='proiect',
            fields=[
                ('id_proiect', models.AutoField(primary_key=True, serialize=False)),
                ('data_inceput', models.DateField()),
                ('buget_alocat', models.IntegerField(max_length=10)),
                ('nume_proiect', models.CharField(max_length=30)),
                ('nume_laborator_desfasurare', models.CharField(max_length=25)),
                ('stadiu_curent', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='terapie',
            fields=[
                ('id_terapie', models.AutoField(max_length=2, primary_key=True, serialize=False)),
                ('nume_terapie', models.CharField(max_length=20)),
                ('durata_in_zile', models.IntegerField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='tratament',
            fields=[
                ('id_tratament', models.AutoField(max_length=4, primary_key=True, serialize=False)),
                ('nume_tratament', models.CharField(max_length=50)),
                ('tip_tratament', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='programare',
            fields=[
                ('id_programare', models.AutoField(max_length=10, primary_key=True, serialize=False)),
                ('data', models.DateTimeField()),
                ('CNP_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Baza_de_date_spital.doctor')),
                ('CNP_pacient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Baza_de_date_spital.pacient')),
            ],
        ),
        migrations.CreateModel(
            name='terapie_inclusa_in_tratament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_terapie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.terapie')),
                ('id_tratament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.tratament')),
            ],
            options={
                'unique_together': {('id_tratament', 'id_terapie')},
            },
        ),
        migrations.CreateModel(
            name='prescrieri_programare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_programare', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.programare')),
                ('id_tratament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.tratament')),
            ],
            options={
                'unique_together': {('id_tratament', 'id_programare')},
            },
        ),
        migrations.CreateModel(
            name='medicamente_continute_de_tratament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.medicament')),
                ('id_tratament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.tratament')),
            ],
            options={
                'unique_together': {('id_tratament', 'id_medicament')},
            },
        ),
        migrations.CreateModel(
            name='doctor_atasat_la_proiect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CNP_doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.doctor')),
                ('id_proiect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Baza_de_date_spital.proiect')),
            ],
            options={
                'unique_together': {('CNP_doctor', 'id_proiect')},
            },
        ),
    ]
