# Generated by Django 4.0 on 2022-01-08 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Baza_de_date_spital', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CabinetMedical',
            fields=[
                ('id_cabinet_medical', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('etaj', models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True)),
                ('corp_cladire', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cabinet_medical',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MedicamenteContinuteDeTratament',
            fields=[
                ('id_medicament', models.OneToOneField(db_column='id_medicament', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Baza_de_date_spital.medicament')),
            ],
            options={
                'db_table': 'medicamente_continute_de_tratament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PrescriptiiProgramare',
            fields=[
                ('id_tratament', models.OneToOneField(db_column='id_tratament', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Baza_de_date_spital.tratament')),
            ],
            options={
                'db_table': 'prescriptii_programare',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TerapieInclusaInTratament',
            fields=[
                ('id_terapie', models.OneToOneField(db_column='id_terapie', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Baza_de_date_spital.terapie')),
            ],
            options={
                'db_table': 'terapie_inclusa_in_tratament',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorAtasatLaProiect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'doctor_atasat_la_proiect',
            },
        ),
        migrations.DeleteModel(
            name='cabinet_medical',
        ),
        migrations.AlterUniqueTogether(
            name='medicamente_continute_de_tratament',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='medicamente_continute_de_tratament',
            name='id_medicament',
        ),
        migrations.RemoveField(
            model_name='medicamente_continute_de_tratament',
            name='id_tratament',
        ),
        migrations.AlterUniqueTogether(
            name='prescrieri_programare',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='prescrieri_programare',
            name='id_programare',
        ),
        migrations.RemoveField(
            model_name='prescrieri_programare',
            name='id_tratament',
        ),
        migrations.AlterUniqueTogether(
            name='terapie_inclusa_in_tratament',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='terapie_inclusa_in_tratament',
            name='id_terapie',
        ),
        migrations.RemoveField(
            model_name='terapie_inclusa_in_tratament',
            name='id_tratament',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='medicament',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pacient',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='programare',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='proiect',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='terapie',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='tratament',
            options={'managed': False},
        ),
        migrations.DeleteModel(
            name='doctor_atasat_la_proiect',
        ),
        migrations.DeleteModel(
            name='medicamente_continute_de_tratament',
        ),
        migrations.DeleteModel(
            name='prescrieri_programare',
        ),
        migrations.DeleteModel(
            name='terapie_inclusa_in_tratament',
        ),
        migrations.AddField(
            model_name='doctoratasatlaproiect',
            name='cnp_doctor_proiect',
            field=models.ForeignKey(db_column='CNP_doctor_proiect', on_delete=django.db.models.deletion.DO_NOTHING, to='Baza_de_date_spital.doctor'),
        ),
        migrations.AddField(
            model_name='doctoratasatlaproiect',
            name='id_proiect',
            field=models.ForeignKey(db_column='id_proiect', on_delete=django.db.models.deletion.DO_NOTHING, to='Baza_de_date_spital.proiect'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoratasatlaproiect',
            unique_together={('cnp_doctor_proiect', 'id_proiect')},
        ),
    ]
